"""Model configs and pair presets for Dual LLM Pro Max"""

MODEL_CONFIGS = {
    "gpt-4o": {
        "provider": "openai_compatible",
        "base_url": "https://api.openai.com/v1",
        "api_key_env": "OPENAI_API_KEY",
        "model": "gpt-4o",
        "label": "GPT-4o (ChatGPT)",
        "family": "openai",
    },
    "o1": {
        "provider": "openai_compatible",
        "base_url": "https://api.openai.com/v1",
        "api_key_env": "OPENAI_API_KEY",
        "model": "o1",
        "label": "o1 (ChatGPT Reasoning)",
        "family": "openai",
    },
    "gpt-4o-mini": {
        "provider": "openai_compatible",
        "base_url": "https://api.openai.com/v1",
        "api_key_env": "OPENAI_API_KEY",
        "model": "gpt-4o-mini",
        "label": "GPT-4o Mini",
        "family": "openai",
    },
    "claude-sonnet": {
        "provider": "anthropic",
        "api_key_env": "ANTHROPIC_API_KEY",
        "model": "claude-sonnet-4-20250514",
        "label": "Claude Sonnet 4",
        "family": "anthropic",
    },
    "claude-opus": {
        "provider": "anthropic",
        "api_key_env": "ANTHROPIC_API_KEY",
        "model": "claude-opus-4-20250514",
        "label": "Claude Opus 4",
        "family": "anthropic",
    },
    "gemini-2.0-flash": {
        "provider": "openai_compatible",
        "base_url": "https://generativelanguage.googleapis.com/v1beta/openai/",
        "api_key_env": "GOOGLE_API_KEY",
        "model": "gemini-2.0-flash",
        "label": "Gemini 2.0 Flash",
        "family": "google",
    },
    "gemini-2.5-pro": {
        "provider": "openai_compatible",
        "base_url": "https://generativelanguage.googleapis.com/v1beta/openai/",
        "api_key_env": "GOOGLE_API_KEY",
        "model": "gemini-2.5-pro-preview-06-05",
        "label": "Gemini 2.5 Pro",
        "family": "google",
    },
    "grok-3": {
        "provider": "openai_compatible",
        "base_url": "https://api.x.ai/v1",
        "api_key_env": "XAI_API_KEY",
        "model": "grok-3",
        "label": "Grok 3 (xAI)",
        "family": "xai",
    },
    "ollama-llama3.1": {
        "provider": "openai_compatible",
        "base_url": "http://localhost:11434/v1",
        "api_key_env": None,
        "model": "llama3.1:70b",
        "label": "Ollama Llama 3.1 70B",
        "family": "local",
    },
    "ollama-qwen2.5": {
        "provider": "openai_compatible",
        "base_url": "http://localhost:11434/v1",
        "api_key_env": None,
        "model": "qwen2.5:72b",
        "label": "Ollama Qwen 2.5 72B",
        "family": "local",
    },
    "lmstudio": {
        "provider": "openai_compatible",
        "base_url": "http://localhost:1234/v1",
        "api_key_env": None,
        "model": "local-model",
        "label": "LM Studio (Local)",
        "family": "local",
    },
}

PAIR_PRESETS = {
    "chatgpt_claude": {
        "a": "gpt-4o", "b": "claude-sonnet",
        "title": "ChatGPT + Claude",
        "desc": "Strong general ability + careful analysis (recommended default)",
        "keys": ["openai", "anthropic"],
    },
    "claude_gemini": {
        "a": "claude-sonnet", "b": "gemini-2.0-flash",
        "title": "Claude + Gemini",
        "desc": "Structured Claude reasoning + fast Google Gemini",
        "keys": ["anthropic", "google"],
    },
    "gemini_grok": {
        "a": "gemini-2.0-flash", "b": "grok-3",
        "title": "Gemini + Grok",
        "desc": "Google speed + xAI truth-seeking style",
        "keys": ["google", "xai"],
    },
    "chatgpt_gemini": {
        "a": "gpt-4o", "b": "gemini-2.0-flash",
        "title": "ChatGPT + Gemini",
        "desc": "OpenAI + Google — broad knowledge and speed",
        "keys": ["openai", "google"],
    },
    "chatgpt_grok": {
        "a": "gpt-4o", "b": "grok-3",
        "title": "ChatGPT + Grok",
        "desc": "Polished GPT answers + Grok perspective",
        "keys": ["openai", "xai"],
    },
    "claude_grok": {
        "a": "claude-sonnet", "b": "grok-3",
        "title": "Claude + Grok",
        "desc": "Careful analysis + maximal truth-seeking",
        "keys": ["anthropic", "xai"],
    },
    "o1_claude": {
        "a": "o1", "b": "claude-sonnet",
        "title": "o1 + Claude",
        "desc": "Deep OpenAI reasoning first, then Claude critique",
        "keys": ["openai", "anthropic"],
    },
    "o1_gemini": {
        "a": "o1", "b": "gemini-2.0-flash",
        "title": "o1 + Gemini",
        "desc": "OpenAI reasoning + Google synthesis",
        "keys": ["openai", "google"],
    },
    "o1_grok": {
        "a": "o1", "b": "grok-3",
        "title": "o1 + Grok",
        "desc": "Deep reasoning + unfiltered Grok review",
        "keys": ["openai", "xai"],
    },
    "claude_opus_gpt": {
        "a": "claude-opus", "b": "gpt-4o",
        "title": "Claude Opus + ChatGPT",
        "desc": "Top-tier Claude depth + GPT versatility",
        "keys": ["anthropic", "openai"],
    },
    "gemini_pro_claude": {
        "a": "gemini-2.5-pro", "b": "claude-sonnet",
        "title": "Gemini Pro + Claude",
        "desc": "Google Pro reasoning + Claude refinement",
        "keys": ["google", "anthropic"],
    },
    "gemini_pro_gpt": {
        "a": "gemini-2.5-pro", "b": "gpt-4o",
        "title": "Gemini Pro + ChatGPT",
        "desc": "Google Pro + OpenAI synthesis",
        "keys": ["google", "openai"],
    },
    "grok_claude_opus": {
        "a": "grok-3", "b": "claude-opus",
        "title": "Grok + Claude Opus",
        "desc": "Truth-seeking first, elite Claude critique",
        "keys": ["xai", "anthropic"],
    },
    "local_cloud": {
        "a": "ollama-llama3.1", "b": "claude-sonnet",
        "title": "Local + Claude",
        "desc": "Private local model + Claude critic (hybrid)",
        "keys": ["anthropic"],
    },
    "universal": {
        "a": "gpt-4o", "b": "claude-sonnet",
        "title": "Universal (Any + Any)",
        "desc": "Freely pick any Model A and any Model B",
        "keys": ["openai", "anthropic", "google", "xai"],
    },
}

SECTION_ORDER = list(PAIR_PRESETS.keys())
